name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags-ignore:
      - 'v*' # version-tagged commits are releases which have their own workflow
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn && yarn ci
